name: Update data every 4 hours

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:
  push:
    branches: ["master"]

jobs:
  run-task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run gomyvip
        shell: bash
        run: |
          cd gomyvip
          go run . > ../data.json
      - name: Setup git
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Commit changes
        shell: bash
        run: |
          git add data.json
          git commit -m "Update data.json"

          git pull --rebase origin master
          git push origin master
      - uses: actions/setup-python@v5
      - name: Generate html table
        shell: bash
        run: |
          pip3 install jtbl
          cat data.json | jtbl -H > data.html

          git add data.html
          git commit -m "Update data.html"

          git pull --rebase origin master
          git push origin master